export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/register'
export const CONTACTS_ROUTE = '/contacts'
export const ADMIN_ROUTE = '/adminPanel'
export const DOCTOR_ROUTE = '/doctorPanel'
export const CAB_ROUTE = '/cab'
export const SCHEDULE_ROUTE = '/schedule'
export const DEPARTMENT_ROUTE = '/department'